name: 'Hugo Build and Deploy'
author: 'Adam Ormsby (@aormsby)'
description: 'Automatically builds and deploys Hugo website, works with submodules'

branding:
  icon: upload-cloud
  color: orange

inputs:
  deploy_directory:
    description: 'Name of Hugo build output folder (path from root directory)'
    required: true
    default: 'public'

  build_branch:
    description: 'Main repo branch used for building the site'
    required: true
    default: 'master'

  deploy_branch:
    description: 'Branch to deploy to if pushing build to submodule'
    required: false
    default: 'master'

    # please use with caution
  fresh_build:
    description: 'If true, clear public directory data before rebuild (ignores files in do-not-delete-files list)'
    required: false
    default: false

    # input as a single string with filenames separated by a space
    # only exact file names are supported at this time
    # these files are already skipped: '. .. .git CNAME'
  do_not_delete_files:
    description: 'Files to skip when cleaning deploy directory with "fresh" option'
    required: false

  commit_message:
    description: 'Appends a custom message to the auto-build commit message'
    required: false

  hugo_build_options:
    description: 'Include additional Hugo build options (single string, space between options)'
    required: false

  git_user:
    description: 'Git user credentials for sigining commit'
    required: false
    default: 'Github Action - Hugo Build and Deploy'

  git_email:
    description: 'Git email credentials for sigining commit'
    required: false
    default: 'action@github.com'

runs:
  using: 'node12'
  main: 'main.js'