name: 'Hugo Build and Deploy'
author: 'Adam Ormsby (@aormsby)'
description: 'Automatically builds and deploys Hugo website, works with submodules'

branding:
  icon: upload-cloud
  color: orange

inputs:
  hugo_publish_directory:
    description: 'Name of Hugo publish directory, Hugo default is "public"'
    required: true
    default: 'public'

  source_branch:
    description: 'Repo branch, data source for site build'
    required: true

  release_branch:
    description: 'Repo branch where site is built and deployed, separated from source branch for easy access to build history'
    required: true
  
  merge_args:
    description: 'Args to pass when merging the source branch into the release branch, default is to take all changes from source'
    required: true
    default: '-s recursive -Xtheirs'

  submodule_branch:
    description: 'If your Hugo build directory contains a submodule (the build output is tracked in another repo), set the deployment branch in that submodule - ignore option if not using a submodule'
    required: false

    # please use with caution
  full_rebuild:
    description: 'If true, clear build directory and build entire site (clear step ignores files in the "do_not_delete_regex" pattern)'
    required: true
    default: false

    # input as a single string with filenames separated by a pipe character
    # saved list is a regex pattern
    # these patterns are saved by default: '^\.+$|^\.git$|^CNAME$'
  do_not_delete_regex:
    description: 'Files to skip when cleaning deploy directory with "full_rebuild" option, regex input required (be careful with special characters like ".")'
    required: false

  commit_message:
    description: 'Appends a custom message to the auto-build commit message'
    required: false

  hugo_build_options:
    description: 'Include additional Hugo build options (single string, space between options)'
    required: false

  git_config_user:
    description: 'Git user credentials for sigining commit, (set to "null" for no config)'
    required: true
    default: 'GH Action - Hugo Deploy to GH Pages'

  git_config_email:
    description: 'Git email credentials for sigining commit (set to "null" for no config)'
    required: true
    default: 'action@github.com'
  
  git_config_pull_rebase:
    description: 'Git config for "pull.rebase" settings, usually recommend false for this action (set to "null" for no config)'
    required: true
    default: 'false'

  test_mode:
    description: 'If set to "true", runs verification test on all inputs and any testable actions that use them'
    required: true
    default: 'false'
  
  strict_mode:
    description: 'If set to "false", hugo builds with warnings will be allowed to proceed. Defaults to "true".'
    required: true
    default: true

  tag_release:
    description: 'Set "true" to tag release with build number'
    required: true
    default: false

runs:
  using: 'node12'
  main: 'main.js'