name: 'Hugo Build and Deploy'
author: 'Adam Ormsby (@aormsby)'
description: 'Automatically builds and deploys Hugo website, works with submodules'

branding:
  icon: upload-cloud
  color: orange

inputs:
  hugo_publish_directory:
    description: 'Name of Hugo publish directory, Hugo default is "public"'
    required: true

  source_branch:
    description: 'Repo branch, data source for site build'
    required: true

  deploy_branch:
    description: 'Repo branch where site is built and deployed, separated from source branch for easy access to build history'
    required: true
  
  source_merge_args:
    description:
    required: false
    default: '-s recursive -Xtheirs'

  submodule_branch:
    description: 'If your Hugo build directory contains a submodule (the build output is tracked in another repo), set the deployment branch in that submodule - ignore option if not using a submodule'
    required: false

    # please use with caution
  fresh_build:
    description: 'If true, clear public directory data before rebuild (ignores files in do-not-delete-files list)'
    required: false
    default: false

    # input as a single string with filenames separated by a space
    # only exact file names are supported at this time
    # these files are already skipped: '. .. .git CNAME'
  do_not_delete_files:
    description: 'Files to skip when cleaning deploy directory with "fresh" option'
    required: false

  commit_message:
    description: 'Appends a custom message to the auto-build commit message'
    required: false

  hugo_build_options:
    description: 'Include additional Hugo build options (single string, space between options)'
    required: false

  git_user:
    description: 'Git user credentials for sigining commit'
    required: false
    default: 'Github Action - Hugo Build and Deploy'

  git_email:
    description: 'Git email credentials for sigining commit'
    required: false
    default: 'action@github.com'

runs:
  using: 'node12'
  main: 'main.js'