name: 'Hugo Build and Deploy'
author: 'Adam Ormsby (@aormsby)'
description: 'Automatically builds and deploys Hugo website, works with submodules'

branding:
  icon: upload-cloud
  color: orange

inputs:
  deploy_repo_github_token:
    description: 'Authentication token for accessing deploy repo'
    required: false

  # theme_repo_github_token:
  #   description: 'Authentication token for accessing theme repo'
  #   required: false

  deploy_directory:
    description: 'name of specified Hugo output folder'
    required: true
    default: 'public'

  build_branch:
    description: 'main repo branch used for building the site'
    required: true
    default: 'master'

  deploy_branch:
    description: 'submodule repo branch to deploy site to'
    required: true
    default: 'master'

	# -f | fresh, deletes public directory data before rebuild (skips files in 'do-not-delete-files' list)
	# -m | message, appends to auto-build commit message, works like 'git -m'
  action_options:
    description: 'additional action options (single string, space between options)'
    required: false

  # these files are always skipped: ".", "..", ".git", "CNAME"'
  do_not_delete_files:
    description: 'files to skip when cleaning deploy directory with "fresh" option'
    required: false

  hugo_build_options:
    description: 'include additional Hugo build options (single string, space between options)'
    required: false

runs:
  using: 'node12'
  main: 'main.js'