name: 'Hugo Build and Deploy'
author: 'Adam Ormsby (@aormsby)'
description: 'Automatically builds and deploys Hugo website, works with submodules'

branding:
  icon: upload-cloud
  color: orange

inputs:
  # github_token:
  #   description: 'Token for accessing the remote repo with authentication'
  #   required: false

  # upstream_repository:
  #   description: 'Upstream repository, e.g. => aormsby/Fork-Sync-With-Upstream-action'
  #   required: true

  # upstream_branch:
  #   description: 'Branch to pull from, default = master'
  #   required: true
  #   default: 'master'

  # target_branch:
  #   description: 'Branch to push to, default = master'
  #   required: true
  #   default: 'master'

runs:
  using: 'node12'
  main: 'main.js'